language: node_js 
dist: trusty

node_js:
  - "6"

before_script:
  - which Xvfb 
  - "export DISPLAY=:99"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 1 # give xvfb some time to start
  - ps xuawww

script:
 - yarn install
 - FOLIO_UI_URL="http://folio-uidemo-test.indexdata.com" DEBUG=nightmare yarn test

